

SELECT DATEPART(YEAR, GETDATE())         --RETORNA O ANO DE UMA DATA
SELECT DATEPART(QUARTER, GETDATE())      --RETORNA O TRIMESTRE DE UMA DATA
SELECT DATEPART(MONTH, GETDATE())        --RETORNA O MÊS DE UMA DATA
SELECT DATEPART(DAYOFYEAR, GETDATE())    --RETORNA O DIA DO ANO DE UMA DATA
SELECT DATEPART(DAY, GETDATE())          --RETORNA O DIA DE UMA DATA
SELECT DATEPART(WEEK, GETDATE())         --RETORNA A SEMANA DE UMA DATA
SELECT DATEPART(WEEKDAY, GETDATE())      --RETORNA UM INTEIRO EQUIVALENTE AO DIA DA SEMANA DE UMA DATA
SELECT DATEPART(HOUR, GETDATE())         --RETORNA A HORA DE UMA DATA
SELECT DATEPART(MINUTE, GETDATE())       --RETORNA O MINUTO DE UMA DATA
SELECT DATEPART(SECOND, GETDATE())       --RETORNA O SEGUNDO DE UMA DATA
SELECT DATEPART(MILLISECOND, GETDATE())   --RETORNA O MILISEGUNDO DE UMA DATA


SELECT DATEDIFF(YEAR, '2000-03-24', GETDATE())      --RETORNA A DIFERENÇA DE ANOS ENTRE AS DATAS
SELECT DATEDIFF(QUARTER, '2000-03-24',GETDATE())    --RETORNA A DIFERENÇA DE TRIMESTRE ENTRE AS DATAS
SELECT DATEDIFF(MONTH, '2000-03-24',GETDATE())      --RETORNA A DIFERENÇA DE MESES ENTRE AS DATAS
SELECT DATEDIFF(DAYOFYEAR, '2000-03-24',GETDATE())  --RETORNA A DIFERENÇA DE DIAS DO ANO ENTRE AS DATAS
SELECT DATEDIFF(DAY, '2000-03-24',GETDATE())        --RETORNA A DIFERENÇA DE DIAS ENTRE AS DATAS
SELECT DATEDIFF(WEEK, '2000-03-24',GETDATE())       --RETORNA A DIFERENÇA DE SEMANAS ENTRE AS DATAS
SELECT DATEDIFF(HOUR, '2000-03-24',GETDATE())       --RETORNA A DIFERENÇA DE HORAS ENTRE AS DATAS
SELECT DATEDIFF(MINUTE, '2000-03-24',GETDATE())     --RETORNA A DIFERENÇA DE MINUTOS ENTRE AS DATAS
SELECT DATEDIFF(SECOND, '2000-03-24',GETDATE())     --RETORNA A DIFERENÇA DE SEGUNDOS ENTRE AS DATAS
SELECT DATEDIFF(MILLISECOND, '2000-03-24',GETDATE()) --RETORNA A DIFERENÇA DE MILISEGUNDOS ENTRE AS DATAS


SELECT DATEADD(YEAR, 1, GETDATE())      --ADICIONA 1 ANO A DATA
SELECT DATEADD(QUARTER, 1,GETDATE())    --ADICIONA 1 TRIMESTRE A DATA
SELECT DATEADD(MONTH, 1,GETDATE())      --ADICIONA 1 MES A DATA
SELECT DATEADD(DAYOFYEAR, 1,GETDATE())  --ADICIONA 1 DIA A DATA
SELECT DATEADD(DAY, 1,GETDATE())        --ADICIONA 1 DIA A DATA
SELECT DATEADD(WEEK, 1,GETDATE())       --ADICIONA 1 SEMANA A DATA
SELECT DATEADD(WEEKDAY, 1,GETDATE())    --ADICIONA 1 DIA A DATA
SELECT DATEADD(HOUR, 1,GETDATE())       --ADICIONA 1 HORA A DATA
SELECT DATEADD(MINUTE, 1,GETDATE())     --ADICIONA 1 MINUTO A DATA
SELECT DATEADD(SECOND, 1,GETDATE())     --ADICIONA 1 SEGUNDO A DATA
SELECT DATEADD(MILLISECOND, 1,GETDATE()) --ADICIONA 1 MILISEGUNDO A DATA

select CHARINDEX ('SQL','Microsoft SQL Server') 

select CHARINDEX ('7.0', 'Microsoft SQL Server 2000') 

Select PATINDEX ('%BC%', 'ABCD') 


--Exemplo de CHARINDEX: 
USE AdventureWorks2012; 
 GO 
 SELECT CHARINDEX ( 'ensure' , DocumentSummary ) 
 FROM Production.Document 
 WHERE DocumentID = 3 ; 
 GO 
 
--Exemplos de PATINDEX: 
USE AdventureWorks ; 
 GO 
 SELECT PATINDEX ( '%ensure%' , DocumentSummary ) 
 FROM Production.Document 
 WHERE DocumentID = 3 ; 
 GO 
 
